### ISSUE TITLE
npm install -g git-commit-gpt

### ISSUE THREAD

**Issue by jamalsoueidan** [nooqta/git-commit-gpt#1]
I installed it globally and it didn't work..

Is there any configuration I need to do for git to find gpt plugin?

**Comment by anis-marrouchi** [comment]
Hello Jamal,
Sorry for the late reply, I got busy these days. I've just updated the doc. You'll need an OpenAI account and do the following step:

```
export OPEN_AI_KEY=your_openai_key
```
Let me know if this resolves the issue.
